# Generated by Django 5.2 on 2025-05-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dustbin', 'Dustbin')], default='approved', max_length=10),
        ),
    ]
