# Generated by Django 5.2 on 2025-05-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_youtubevideo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dustbin', 'Dustbin')], default='pending', max_length=10),
        ),
    ]
