
# CATEGORY_KEYWORDS = {
#     "Quran": ["quran", "quran recitation", "surah", "tilawah"],
#     "Technology": ["ai", "machine learning", "coding", "software", "programming"],
#     "Motivation": ["motivation", "inspirational speech", "self improvement"],
#     "Business": ["startup tips", "entrepreneurship", "marketing strategy"],
#     "Politics": ["current affairs", "election news", "political debate"],
#     "Education": ["study tips", "academic lectures", "online classes"],
#     "Languages": [
#     "language learning",
#     "learn languages",
#     "english grammar",
#     "spoken english",
#     "learn english",
#     "basic english",
#     "english conversation",
#     "english speaking practice",
#     "swahili lessons",
#     "learn swahili",
#     "french lessons",
#     "learn french",
#     "german language",
#     "learn german",
#     "spanish course",
#     "learn spanish",
#     "arabic language",
#     "learn arabic",
#     "chinese for beginners",
#     "learn chinese",
#     "mandarin lessons",
#     "italian language",
#     "learn italian",
#     "hindi language",
#     "learn hindi",
#     "russian lessons",
#     "learn russian",
#     "korean language",
#     "learn korean",
#     "japanese for beginners",
#     "learn japanese",
#     "language tips",
#     "language tricks",
#     "english vocabulary",
#     "pronunciation practice",
#     "language hacks",
#     "duolingo",
#     "polyglot tips",
#     "language apps",
#     "foreign language learning",
#     "language exchange",
#     "multilingual learning",
#     "language immersion"
# ]

# }
